[package]
name = "libdivsufsort-sys"
version = "0.1.0"
authors = ["baku <bahkhun@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1.45"
bindgen = "0.58.1"